function aboutBody(){
    const mainBody=document.getElementById("mainBody")
    document.getElementById("mainBody").innerHTML = ""; 

    const description=document.createElement("div")
    description.classList.add("menuBody")

    const divContent=document.createElement("div")
    divContent.classList.add("aboutMainDiv")

    const divHours=document.createElement("div")
    divHours.classList.add("divHours")

    const divHoursTitle=document.createElement("h2")
    divHoursTitle.innerHTML=("Hours")
    
    const divBurgahs=document.createElement("div")
    divBurgahs.classList.add("divBurgahs")

    const divBurgahsTitle=document.createElement("h2")
    divBurgahsTitle.innerHTML=("Burgahs")
    
    const divh1=document.createElement("h3")
    divh1.innerHTML=("Sunday 8am - 8pm")
    const divh2=document.createElement("h3")
    divh2.innerHTML=("Monday 6am - 6pm")
    const divh3=document.createElement("h3")
    divh3.innerHTML=("Tuesday 6am - 6pm")
    const divh4=document.createElement("h3")
    divh4.innerHTML=("Wednesday 6am - 6pm")
    const divh5=document.createElement("h3")
    divh5.innerHTML=("Thursday 6am - 10pm")
    const divh6=document.createElement("h3")
    divh6.innerHTML=("Friday 6am - 10pm")
    const divh7=document.createElement("h3")
    divh7.innerHTML=("Saturday 8am - 10pm")

    divBurgahs.append(divBurgahsTitle)

    const burgah1div=document.createElement("div")
    burgah1div.classList.add("burgah1div")
    const burgah1=document.createElement("span")
    burgah1.classList.add("burgah1")
    burgah1.innerHTML=("Cool Burgah")
    const brugah1dots=document.createElement("span")
    brugah1dots.classList.add("brugah1dots")
    const brugah1price=document.createElement("span")
    brugah1price.classList.add("brugah1price")
    brugah1price.innerHTML=("$42.99")
    burgah1div.appendChild(burgah1)
    burgah1div.appendChild(brugah1dots)
    burgah1div.appendChild(brugah1price)
    divBurgahs.appendChild(burgah1div)

    const burgah2div=document.createElement("div")
    burgah2div.classList.add("burgah1div")
    const burgah2=document.createElement("span")
    burgah2.classList.add("burgah1")
    burgah2.innerHTML=("Ugly Burgah")
    const brugah2dots=document.createElement("span")
    brugah2dots.classList.add("brugah1dots")
    const brugah2price=document.createElement("span")
    brugah2price.classList.add("brugah1price")
    brugah2price.innerHTML=("$15.99")
    burgah2div.appendChild(burgah2)
    burgah2div.appendChild(brugah2dots)
    burgah2div.appendChild(brugah2price)
    divBurgahs.appendChild(burgah2div)

    const burgah3div=document.createElement("div")
    burgah3div.classList.add("burgah1div")
    const burgah3=document.createElement("span")
    burgah3.classList.add("burgah1")
    burgah3.innerHTML=("Zesty Burgah")
    const brugah3dots=document.createElement("span")
    brugah3dots.classList.add("brugah1dots")
    const brugah3price=document.createElement("span")
    brugah3price.classList.add("brugah1price")
    brugah3price.innerHTML=("$15.99")
    burgah3div.appendChild(burgah3)
    burgah3div.appendChild(brugah3dots)
    burgah3div.appendChild(brugah3price)
    divBurgahs.appendChild(burgah3div)

    const burgah4div=document.createElement("div")
    burgah4div.classList.add("burgah1div")
    const burgah4=document.createElement("span")
    burgah4.classList.add("burgah1")
    burgah4.innerHTML=("Shiny Burgah")
    const brugah4dots=document.createElement("span")
    brugah4dots.classList.add("brugah1dots")
    const brugah4price=document.createElement("span")
    brugah4price.classList.add("brugah1price")
    brugah4price.innerHTML=("$21.99")
    burgah4div.appendChild(burgah4)
    burgah4div.appendChild(brugah4dots)
    burgah4div.appendChild(brugah4price)
    divBurgahs.appendChild(burgah4div)

    divHours.appendChild(divHoursTitle)
    divHours.appendChild(divh1)
    divHours.appendChild(divh2)
    divHours.appendChild(divh3)
    divHours.appendChild(divh4)
    divHours.appendChild(divh5)
    divHours.appendChild(divh6)
    divHours.appendChild(divh7)


    divContent.appendChild(divBurgahs)
    divContent.appendChild(divHours)
    description.appendChild(divContent)
    mainBody.appendChild(description)
    return
}
export {aboutBody}